### ISSUE TITLE
Test setup?

### ISSUE THREAD

**Issue by nikitalita** [malacalypse/rp2040_i2s_example#1]
What was the test setup that you used for this, i.e. what hardware did you use? There don't seem to be any breakout boards for the PCM3060 or the WM8731 available...

**Comment by malacalypse** [comment]
Use any I2S-compatible codec you want. I've used this with a variety of codecs.

**Comment by nikitalita** [comment]
Right, but did you have drivers for them?

**Comment by malacalypse** [comment]
I won't be providing any chip-specific code here, if that's your question. All any of those codecs need are a few I2C commands to enable the I2S interface, anyway, but that's not a concern of this library, which is focused on the I2S hardware implementation.
