### ISSUE TITLE
i2s_program_start_slaved

### ISSUE THREAD

**Issue by OscarTofa** [malacalypse/rp2040_i2s_example#2]
Hi 

We are trying to make slave mode work. We are interfacing with an Adau1761 codec in the following way but without succes
Codec Master
Bit cklock 3.072MHz
FS 48Khz
What parts of the program need to be edited to be compatible with this signal? 
With the i2s_program_start_synched mode we were able to make it work without problems

Kind Regards

**Comment by malacalypse** [comment]
Sorry, I cannot provide individual situational support for this. You'll have to work through the docs and understand it on your own. The slave drivers will work perfectly fine with a standard I2S signal, however, and should not need any editing, so if you are having trouble with them, please check the signals and timing of the codec on an oscilloscope to be sure they are looking correct and that you have wired them to the correct pins.
