### ISSUE TITLE
Clarify the pin configuration

### ISSUE THREAD

**Issue by appliedsine** [malacalypse/rp2040_i2s_example#3]
Hey man, first of all thank you for this awesome implementation, the double buffering, the write up, super thankful for this great work.  On to my issue, if it's not too much trouble, can you please clarify the nomenclature you used for pin setup?  In the README you have the example

'For instance, a useful set of choices on a default Pico would be:

SCK: 10
DOUT: 6
DIN: 7
Clock_Pin_Base: 8 '

Are these pin numbers referencing the Pico boards pin numbering system? Or are they a reference like GPIO_<number>, or are they a reference to the actually pins on the RP2040?  

Thanks again!

**Comment by malacalypse** [comment]
You're welcome, I'm glad you find it useful. 

The Pico C SDK uses entirely GPIO pin numbers, not Pico board pin numbers. If you get confused, there's an image in the Pico datasheet which shows you how the GPIO pin numbers map to the Pico board's physical pins.
